project_id = "vxzktyklzkfqitptzctk"

[functions.import-auth-users]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.migrate-atividade-fotos-auto]
verify_jwt = false

[functions.asaas-configure-webhook]
verify_jwt = false
