project_id = "vxzktyklzkfqitptzctk"

[functions.import-auth-users]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.migrate-atividade-fotos-auto]
verify_jwt = false

[functions.asaas-configure-webhook]
verify_jwt = false

[functions.push-vapid-public-key]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.change-password]
verify_jwt = false

[functions.send-to-carreira]
verify_jwt = false

[functions.sync-all-to-carreira]
verify_jwt = false
